/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPortfolioReportRegistry {
    function publishReport(address portfolio_owner, uint256 subject_id, bytes32 root_hash, bytes32 attestation_hash) external;

    function getReport(bytes32 root_hash) external view returns (address, uint256, address, uint256, bytes32, bytes32);

    function reportCount(uint256 subject_id) external view returns (uint256);

    function reportAt(uint256 subject_id, uint256 index) external view returns (bytes32);

    error AlreadyPublished(bytes32);

    error EmptyRootHash();

    error ZeroPortfolioOwner();

    error ReportIndexOutOfBounds(uint256, uint256);
}
