/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ISwapReplayVerifier {
    function publishReplay(address portfolio_owner, uint256 subject_id, address pool, uint64 from_block, uint64 to_block, uint32 swap_count, bytes32 input_root, bytes32 result_hash, bytes32 attestation_hash, bytes32 tee_image_hash) external returns (bytes32);

    function getReplay(bytes32 replay_id) external view returns (address, uint256, address, uint256, address, uint256, uint256, uint256, bytes32, bytes32, bytes32, bytes32);

    function replayCount(uint256 subject_id) external view returns (uint256);

    function replayAt(uint256 subject_id, uint256 index) external view returns (bytes32);

    function computeReplayId(address portfolio_owner, uint256 subject_id, address pool, uint64 from_block, uint64 to_block, uint32 swap_count, bytes32 input_root, bytes32 result_hash, bytes32 attestation_hash, bytes32 tee_image_hash) external view returns (bytes32);

    function computeFee(uint256 amount_in, uint32 fee_pips) external view returns (uint256, uint256);

    error AlreadyPublished(bytes32);

    error EmptyInputRoot();

    error EmptyResultHash();

    error EmptyAttestationHash();

    error InvalidBlockRange(uint64, uint64);

    error InvalidSwapCount(uint32);

    error ReplayIndexOutOfBounds(uint256, uint256);

    error ZeroPool();

    error ZeroPortfolioOwner();
}
