/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPortfolioRiskEngine {
    function computeRisk(uint256 total_positions, uint256 out_of_range_positions, uint256 dust_positions, uint256 correlated_exposure_bps, uint256 concentration_bps) external view returns (uint256, uint8, uint8);
}
